### ISSUE TITLE
1. Adopting a general approach to spatial feature data

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#1]
There are two parts to this issue:
1. How do we assign identifiers to specific feature types?
2. How do we link attributes to features?

**Comment by phillipsp73** [comment]
From the working group discussion 8 June. 
The formats commonly used are GeoJSON and ESRI. Do we use GeoJSON as our starting format for implementation?

A couple of other points that were raised:
- The notation of the co-ordinates being used should be defined.
- The projection format should also be included in the meta data.

**Comment by cookeac** [comment]
A starting point would be to design objects that could be included within the "properties" of a GeoJSON feature object. Such objects could also stand on their own (for non-spatial use, or combined with a different geographic interchange format).

For those wishing to use GeoJSON (preference of much of the group), we noted that the only supported coordinate system under the IETF-standardised [RFC-7946](https://datatracker.ietf.org/doc/html/rfc7946) is WGS84 lat-long.

**Comment by GMAPSNZ** [comment]
Possibly outside of MVP for a general approach, but how to define quality assurance of the objects created? Possibly for MetaDataType, but is there a place inside the properties to link to a metadata profile or provide a key element that describes the data's quality? Why it was made, what the source of the data was?

With the increase in precision agriculture and detailed mapping, knowing about the data behind the decisions is important, and helps to understand business risks and opportunities. There's a big difference between object of the slope class of NZLRI, and that generated from a 1m Digital Elevation Model of LiDAR. Even then, knowing the source of the terrain model will help understand any noise or issues with the data, if there was terrain correction applied, and so on. Understanding the collection and purpose of the object will ensure the best data is used for decision making. 

OK, there's the ANZLIC Metadata Profile, but it may be too much work for the casual user to create, or to link to. But a feature I put effort into is the Abstract. It’s a free text entry, that allows key words to describe the context of the data layer. I’ve also found the field Lineage extremely useful to convey information about how the data came to be, why it was collected, and any data statements I feel are needed. I do note there’s other places in the ANZLIC Guidelines about where to put data quality … but IMHO the abstract and lineage about the data collection will be useful for future users of the data.

[As an aside, there's image quality statements that may be of use, but as they're not easily human-readable it could be difficult to understand what the 0s an 1s mean].
