### ISSUE TITLE
Common Meta Data

### ISSUE THREAD

**Issue by cookeac** [Datalinker-Org/Geospatial#10]
In the ICAR group we found it was useful to define an object that provided meta-data (data about the data) that could be applied to all of the objects (features, in our case, but potentially other resources too in future).

| Attribute | Type | Comment |
| ---------- | ---- | ------- |
| SourceIdentifier | FeatureIdentifier | Original scheme and ID of the object in its source (creator) system. The scheme might be a system identifier rather than a well-known scheme or official ID, in which case the ID should be a UUID generated by the source system. |
| created | ISO date time | Date and time the feature was created digitally (not when it actually came into existence!) |
| modified | ISO date time | Date and time the feature was modified (digitally). |
| creator | string | Person or organisation who created the digital feature. |
| validFrom | ISO date time | Date from which this feature is valid or is considered to have exist. Null if forever in the past. |
| validTo | ISO date time | Date up to which this feature is valid. Null if the feature is still valid at present. |

There may be other fields. I propose we create this as a JSON object and then can include it by $ref into the various feature objects.

**Comment by MikePetersNZ** [comment]
What about using an agreed ontology. Is there already one.

**Comment by cookeac** [comment]
This is drawn from the Dublin Core ontology for meta data.
