### ISSUE TITLE
"Place" - Contact Point or location for holdings (or other features)

### ISSUE THREAD

**Issue by cookeac** [Datalinker-Org/Geospatial#12]
At our meeting on [15 June 21](https://github.com/Datalinker-Org/Geospatial/wiki/Working-group-meeting-15-June-2021) we discussed how it might be useful to have contacts or contact points for holdings.

For instance - the dairy vat, the urea silo, the manager's house.
A solution could be a feature object (point feature) with attributes based on the [schema.org Place type](https://schema.org/Place).
This includes an [address](https://schema.org/PostalAddress) object that seems to be reasonably compatible with NZ Post and rural addressing.

We could also represent people contact details (but implementers should be aware Privacy Act requirements) using the [schema.org Person type](https://schema.org/Person).

**Comment by cookeac** [comment]
You can now do the following:
* Define your related entity using a JSON schema version of the [schema.org](https://schema.org) entities. Use the forked repository at https://github.com/Datalinker-Org/schema-org-json-schemas.
* Link to these related objects from any spatial resource using the *Links* array.

**Comment by cookeac** [comment]
After the scope discussion at our [6 April 2022 meeting](https://github.com/Datalinker-Org/Geospatial/wiki/Working-Group-Meeting---6-April-2022), I thought it would be useful to raise this item again for discussion about "places".

If we had a method of categorising places, we could use a spatial resource with a name, address, and other attributes to represent:
- Service points
- Entry and Exit points
- Monitoring sites
- Feedpads
- Evacuation sites
- Nesting sites

I suggest the following attributes from [schema.org](https://schema.org/Place)'s `Place` type would be relevant
- id and identifiers (list) - we have these in spatial resources already
- name (already in spatial resources)
- address
- globalLocationNumber
- hasMap (a URL to a separate visual mapping resource)
- logo (a URL to a separate logo or icon)
- keywords (a text field with comma separated keywords)
- isicV4 - industry classification code for type of business carried out
- publicAccess (boolean - true/false)
- telephone (telephone contact)

In addition to this we would need a categorisation method - which could either be a schema-based categorisation, such as the [NZ Geospatial Data Dictionary Entities](https://docs.topo.linz.govt.nz/data-dictionary/tdd-index-ent-A.html) (e.g. "nz.geospatial.monitoring-site") OR by defining new resource type classes for each category (e.g. MonitoringSiteResource)

**Comment by cookeac** [comment]
Adding this URL so I don't lose it - a PDF with the full list of LINZ [NZ TOPO feature types v 3.5](http://www.ollivier.co.nz/product/topo/topo2020/ddnztopo_V3.5/document/FScodesABC.pdf)

**Comment by MikePetersNZ** [comment]
Andrew, my thought would again go down the minimum viable product path and only add the attributes absolutely necessary and then leave the door open for further additions based on demand from actual working system integrations. I think this will be a long haul.
