### ISSUE TITLE
"Plots" - paddocks, maturity areas, subblocks - definition and attributes

### ISSUE THREAD

**Issue by cookeac** [Datalinker-Org/Geospatial#13]
The INSPIRE Plot is roughly equivalent to an arable crop area, pastoral paddocks, or small management units in vine and tree crops (hence the title to get us all thinking).

Please respond to this issue with suggestions and thoughts in the following format:

**Your use case area (e.g. "livestock in paddocks")**
- suggested attribute
- suggested attribute
... etc

At the **29 June 2021** meeting we will discuss and decide whether there is a general "Plot" with attributes that apply to many things, specific feature types for your use cases, or something inbetween.

**Comment by cookeac** [comment]
**Consider "permanent" vs "seasonal" (and leave events to later)**

In general
[size, purpose/activities, parent, soil type and land use suitability, paddock and block area, climate, slope] 
yield or productivity, establishment date, species, variety
irrigated, dry land

- Paddock
(potentially modelled: nutrient losses - N, sediment, P, carbon stored, carbon traded)
fencing type, location of entrance gates (separate features? linked)

- Plot for potatoes or other vegetable crops
Entry, Cultivar number, seed reference number, inspection number, NZGAP number, History (previous crops over last 4-5 years)

- Reinspection Area

- Stop bank
- Spread Area
- Subblock
clone, row spacing, vine spacing, rootstock, trellis type, (transactional: predominant picking type, quality tier, wine style)

- Field and/or block arable

- Headlands

- Buildings and/or non-growing area
- Holding pens
- Raceways (fenced area as opposed to the line feature), non-productive areas

- Forest stand
Qualify for sequestration offset, carbon credited

**Comment by rogerwanless** [comment]
Non-productive areas could also include native bush and wetlands.

**Comment by cookeac** [comment]
I thought that native bush, wetlands (and indeed perhaps some of our non-productive areas and even forest stands) might be best as other Feature Types. I've been looking into this in the INSPIRE specifications, where they are indeed classified separately, but just as general categories of a "Land Cover Area" polygon - which seems too high-level to me.
