### ISSUE TITLE
2. Being able to cross reference multiple identifiers

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#2]
To handle multiple ways of identifying the same feature we could use identifier schemes. Are there are some well known schemes we could utilise?

**Comment by cookeac** [comment]
My recommendation:

1. Define an identifier type for instance a FeatureIdentifier which is a composite key containing:

| Component | Type | Notes |
| ------------- | ----- | ------- |
| scheme | string | A unique identifier for the scheme that issues the IDs, typically in reverse domain format (e.g. nz.govt.linz) |
| id | string | The identifier within the scheme. |

This would be complimented by a register of well-known schemes

2. Each feature object to have an array of FeatureIdentifiers, allowing its various IDs to be cross-referenced. Organisations don't have to know how to handle all identifiers, just to preserve them if interchanged.
