### ISSUE TITLE
3. Defining and handling relationships between spatial entities

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#3]
If a farm is a parent, is a block it's child? How do we relate the spatial data of features to each other? If a feature is dependent on or belongs to another feature, should we link them?

**Comment by GMAPSNZ** [comment]
We're also using terms like block. "Block" in terms of whenua Māori is a legal area. Perhaps a taxonomy of terms that we can use may assist in explaining technical terms to the wider community.
It's possibly just the same as geospatial industry terms area/polygon/feature class and so forth.

**Comment by cookeac** [comment]
@TerryFirma's comment is a good one. In many ways, "block" has too many meanings (it would be good listed as a synonym in a data dictionary, but not a principle item). 
More precise terms might be:
- Land Management Unit
- Land Title or Cadastral Title (I think LINZ may now talk about "Register Polygons", which are polygons that correspond to an entry in a land register).
-  etc

**Comment by cookeac** [comment]
Regarding @phillipsp73 [comment](https://github.com/Datalinker-Org/Geospatial/issues/7#issuecomment-865463327) on #7 A good structure for references to other entities, which we could use generally would seem to be:

| Attribute | Type | Comment |
| --- | --- | --- |
| relationship | string | type of relationship, from a master list or [FOAF ontology](http://www.foaf-project.org/) |
| type | string | Object type name of the referenced object (e.g. Person, Holding...) |
| id | string | UUID primary identifier of the referenced object in the source system |
| url | string | URL to the referenced object |
