### ISSUE TITLE
Initial discussion of feature types that should be considered

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#4]
To start with we will focus on farm boundaries, blocks/land management units, paddocks, fields.

i.e. What is a farm boundary and how is it determined? e.g cadastral boundaries
How can we capture what the spatial data is representing and share it accurately?

**Comment by cookeac** [comment]
See also Farm Data Standards:
- https://github.com/Datalinker-Org/Farm-Data-Standards/blob/master/Farm%20Features%20and%20Attributes/FFADS_Feature-Catalogue.md
- https://github.com/Datalinker-Org/Farm-Data-Standards/blob/master/Farm%20Features%20and%20Attributes/FFADS_Feature-Attributes-Data-Dictionary.md#Plot-Special-Case-Attributes

**Comment by GMAPSNZ** [comment]
"Blocks" have meaning in whenua Māori as the entire legal land parcel, so may not always be useful as a standard. The Farm Data Standard is a much better way of explaining the use of the block! :-)

[being new to github, if answered by geospatial .3 then feel free to remove this :-) ]

**Comment by cookeac** [comment]
At our meeting this week we noted the difference between "owned" land Whenua Māori and other ownership and "operating" land (Jason's "Land_" prefix in the regional council example).

**Homework for this week**
Let's develop some "use cases" looking at how the "INSPIRE-inspired" feature types we discussed (_holdings, sites, plots_) might (or might not) work in your specific use case. What questions do they raise? What additional attributes might you need?

**Comment by MikePetersNZ** [comment]
Use case examples
+ Public walkways over private land. Some surveyed, some not. Some legal, some "annual bottle of whisky".
+ Community biodiversity projects that cross multiple holdings and public land by human agreement
+ Beekeeper locating hives on multiple holdings
+ Hedge cutting contractor doing a run of hedges down a road

**Comment by cookeac** [comment]
Nice! thank you!
> Use case examples
> * Public walkways over private land. Some surveyed, some not. Some legal, some "annual bottle of whisky".
This would seem to be a "tracks" multi-line resource. The question might be the relationship between the track (or section thereof) and the a) cadastral polygons and their owner and b) holding (operating farm) e.g. for H&S purposes?

> * Community biodiversity projects that cross multiple holdings and public land by human agreement
So potentially multiple views of this: The community project needs to manage its project polygons. However, the land owner might have a cadastral boundary x project slice related to the agreement. The holding (operating farm) might have a holding x project slice for land management purposes?

> * Beekeeper locating hives on multiple holdings
I wouldn't want to divert the group, but I'd love a discussion sometime when time allows on whether hives are just point feature objects (with related data) or whether there is the concept of a "holding" or equivalent for bees to avoid over-placement of hives :-)

> * Hedge cutting contractor doing a run of hedges down a road
This would seem like an activity (planned and actual views) of the multi-line feature that is the hedge cutting?

**Comment by MikePetersNZ** [comment]
MP
Public walkways over private land. Some surveyed, some not. Some legal, some "annual bottle of whisky".

AC
This would seem to be a "tracks" multi-line resource. The question might be the relationship between the track (or section thereof) and the a) cadastral polygons and their owner and b) holding (operating farm) e.g. for H&S purposes?

MP
A further dig into the first one. Bob and Alice are heading out for their weekend tramp. They access the track via a private farm road which is closed to trampers during lambing. Mary the farmer spots some new lambs so changes the farm road status to "closed for lambing" on her farm management software. Bob and Alice now see that the road access is now closed on the "FMC tracks website", the "DOC tracks website" and on their smartphone "tracks of NZ" app.

**Comment by scampbel73** [comment]
Some high level Use cases:
1. Extracting data from one system and being able to be loaded into another with minimal transformation. Data to include farm and paddock boundaries with some relating attributes.
2. Creation of geospatial web services which can be securely accessed  by different systems as a basis for related eg operational data.
3. Ability to use standardised data as basis for compliance reporting.
