### ISSUE TITLE
5. How do we handle temporal changes

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#5]
When the spatial data for a feature changes over time, how are relationships with other features affected? Or activities?
How can changes be defined to allow easy traceability?

**Comment by MikePetersNZ** [comment]
One simple robust trick I used in a project years ago was to have a date column and a current use flag column in the ESRI geodatabase and shapefile. The whole history was there via a filter. It was many years ago so my memory might be a bit rusty. I think JTX was used as well.

So over time, different polygons could be created on the same layer that mapped changes on the ground. In my case it was overlapping tree planting areas year by year.

**Comment by cookeac** [comment]
In the ICAR specs we used a Meta Data sub object, which had _validFrom_ and _validTo_ date-time fields. If _validTo_ was not set, then the object could also be considered "current".
Systems that used data from this interface could then check the validity dates to decide what to display, or whether an activity date falls within the validity period.

**Comment by cookeac** [comment]
Further to this, see issue #10 which brings together common meta data.

**Comment by cookeac** [comment]
Resolved by MetaDataType - validFrom and validTo.
