### ISSUE TITLE
Definition of a holding and its properties

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#7]
Defining the attributes of a holding, starting fields. What else would we like to add to represent a holding?

Field | Type | Description
------|-------|------------
id | string | Unique identifier in the source system
identifiers | array of strings | Array of unique URN identifiers
name | string | Display name of the holding
dateValidFrom | ISO 8601 DateTime | The timestamp the holding details were recorded
dateValidTo | ISO 8601 DateTime | The timestamp the holding details were replaced with new details

**Comment by phillipsp73** [comment]
Attributes of a block - how is it defined? what is it used for?  Activities and events are time dependent and take place on a block.
Attribute | Description
--|--
Size/area | Area of the block 
Primary activity(s) | pasture, crop, orchard, forestry, wetland, riparian, vineyard, structures, pond?, native bush.
Secondary activity | grazing, supplements, runoff 
Parent holding Id | The holding(s) this block belongs to

**Comment by cookeac** [comment]
* Geometry (of course)
* Link or embedded information about relevant contacts - eg. owner, manager, ... What about a "primary contact"?
* Area (also can be calculated) - Aggregate sum of the polygons that make up the holding. In SI units (metres).
* Descriptor for the area - or a prefix; for example land area, cadastral area, etc - to add context Would Productive area be one of these?
* Is this a logical or physical feature? E.g. it is an aggregation of multiple polygons.
* Linkages between features - for instance, the sites related to a holding, other land management units (wetlands). 
* * Parents and children?
* * Links or relationships between features of different types
* * Labels or types of relationships - potentially also security
* Address? Or coordinates of address points for different purposes. What about a "primary address" like an address for service?
* Be aware there can be multiple addresses over times, and also aliases. We might not want to have to handle all of that. Also "local addresses - navigation on site". Also "What three words".

**Comment by phillipsp73** [comment]
In reference to handling different forms of addresses. Could we use a reference?

 primaryContactPlace 
{
type of thing
relationship
identifier
URL (link)
}

**Comment by cookeac** [comment]
Potential attributes for a **Holding** feature

*All the attributes of the base class (#11) plus:*
| Attributes | Type | Comment |
| --- | --- | --- |
| totalArea | number | Total area of all polygons that form the holding, in square metres (or should we allow for different units?) |
| catalogURL | string | URL to retrieve a feature catalogue of all the features held by the server that are relevant to this holding. |

Places (address points) and other linked entities would be dealt with by the **related** array in the base class.
Other feature types (e.g. sites, cadastral boundaries, tracks) would be dealt with through the feature catalogue.

Thoughts? Other attributes?
