### ISSUE TITLE
Definition of a site and its properties

### ISSUE THREAD

**Issue by phillipsp73** [Datalinker-Org/Geospatial#8]
Defining the attributes of a site (Farm Block, Management Block, Land Management Unit ([LMU]Land Management Unit))
What else would we like to add to represent a site?

Field | Type | Description
--|--|--
id | string  | Unique identifier in the source system
identifiers | array of strings | Array of unique URN identifiers
name | string | Display name of the site
dateValidFrom | ISO 8601 DateTime | The timestamp the site details are relevant from (or recorded)
dateValidTo | ISO 8601 DateTime | The timestamp the holding details were replaced with new details
featureList | URL to get array | URL for getting a list of features on a site

**Comment by phillipsp73** [comment]
Attributes of a site - how is it defined? what is it used for?  Activities and events are time dependent and take place on a site.
Attribute | Description
--|--
Size/area | Area of the site (or is this worked out from the spatial data)
Primary activity(s) | pasture, crop, orchard, forestry, wetland, riparian, vineyard, structures, pond?, native bush.
Secondary activity | grazing, supplements, runoff 
Parent holding Id | The holding(s) this block belongs to

Can we then include attributes that are optional and more system specific?
OtherAttributes {
Name:  (Topography, annual rainfall, temp, PET, coastal proximity)
Value:
}

**Comment by MikePetersNZ** [comment]
How and where would the use relationship between holding and site be handled?
For example, Holding A owns site no 1, and Holding B leases site no 1.
